### ISSUE TITLE
TODO List Excel placas

### ISSUE THREAD

**Issue by CesarAscencioV** [prestemos/planning#178]
https://docs.google.com/spreadsheets/d/1WBcAgx0-nlS_Oko3fcXQ4ZsCmbUl8gtUImA_duSMGh4/edit#gid=1946324863

- [ ] Las solicitudes solo deben llegar al módulo de placas cuando se haya dado el VoBo contrato y tenencia cargada.
- [x] Quitar filtro de Expediente recibido
- [x] Quitar los filtros de Tipo vehículo y Trámite
- [x] Cambiar Días en bandeja por Tiempo en bandeja.
- [x] Agregar 2 campos para cargar: Comprobante de baja de placas y Recibo de pago de baja de placas,
- [x] Juntar todas las tabs de las secciones en una sola (como en contratos).
- [x] Cambiar labels de etapas en Dashboard
- [x] Agregar un filtro de Proveedor/Gestor en los nuevos estatus (tabs) a partir del 2.
- [x] En el estatus 7 sí tener un filtro de rango de fechas.
- [x] Agregar una Validación manual de las evidencias del trámite para autorizar pago a proveedor.
- [x] Habilitar envío de incidencias al proveedor.
- [x] Aclarar si vamos a permitir que elijan Agencia como proveedor para el trámite de placas.
- [ ] Que el campo de dirección aparezca para todos los proveedores, no solo para AVM.
- [ ] Investigar porqué al momento de iniciar el trámite ya aparecen cargados los documentos si no lo hizo Luis.
- [ ] Configurar que solo aparezcan proveedores disponibles en ese estado
- [x] Definir la lista de documentos necesarios para el expediente por: trámite y tipo de vehículo.
- [ ] Arreglar bug: cuando el proveedor envía una incidencia en un documento, todos los documentos se marcan con incidencia .
- [ ] Agregar la opción de subir documento adicional.
- [ ] Ordenar todos los procesos de los clientes por Fecha de envío de expediente.
- [ ] Ocultar todas las fechas de la actividad del proceso de los clientes, solo mostrar la última actividad (fecha) del paso en que se quedó.
- [ ] Bug: el estatus del expediente aparece como En validación (ya se envió al proveedor), pero el botón de Enviar expediente a proveedor sigue apareciendo.
- [ ] Agregar campos para subir la Línea de captura y la factura del pago de derechos como evidencias del trámite en la plataforma.
- [ ] Agregar un campo para que puedan subir ese el Acuse de recibo que firma el cliente como parte de paso final de la entrega de placas.
- [x] Decidir qué es mejor: que el gestor contacte directamente al cliente o que nosotros coordinemos con el cliente por medio del EP.
- [ ] Agregar una opción del lado derecho del cotizador que diga si se trata de placas de carga o placas particulares, dependiendo de si el modelo lo permite.
- [ ] Agregar una sección para cargar pago de tenencia y definir quién le va a dar VoBo.
- [ ] Definir en qué momento se decide qué trámites se tienen que realizar (en seminuevos).
